### ISSUE TITLE
Which Ubuntu 20.04

### ISSUE THREAD

**Issue by UmithanGoktolga** [teksander/geth-argos#1]
**Ubuntu20.04**  (http://old-releases.ubuntu.com/releases/20.04.0/)

or

**Ubuntu 20.04.6 LTS (Focal Fossa)**  (https://releases.ubuntu.com/20.04/)

Thank you!

**Comment by Pold87** [comment]
You can use Ubuntu 20.04.6 LTS (Focal Fossa). Also Ubuntu 22.04.4 LTS should work. Only 24.04 LTS is not working currently.
